# Generated by Django 6.0.3 on 2026-03-22 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0002_alter_session_options_session_end_time_and_more'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='room.seat'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='room_capacity',
        ),
        migrations.RemoveField(
            model_name='session',
            name='room_name',
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='room.room'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='movie_sessions.session'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
