# Generated by Django 6.0.3 on 2026-03-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0003_alter_ticket_seat_remove_session_room_capacity_and_more'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='room.room'),
        ),
    ]
