# Generated by Django 6.0.3 on 2026-03-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_sessions', '0005_reservation'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='room.room'),
            preserve_default=False,
        ),
    ]
